using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PlaxionMediator.SourceGenerators;

internal static class SourceEmitter
{
    public static string EmitRegistration(GenerationModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using PlaxionMediator.Abstractions;");
        sb.AppendLine("using PlaxionMediator.Core;");
        sb.AppendLine("using PlaxionMediator;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.Append("namespace ").Append(model.RootNamespace).AppendLine(".Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class PlaxionMediatorRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        PlaxionMediatorGeneratedRegistrationBridge.Register = Register;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static void Register(IServiceCollection services, PlaxionMediatorOptions options)");
        sb.AppendLine("    {");

        foreach (RequestHandlerModel handler in model.RequestHandlers)
        {
            sb.Append("        services.TryAdd(new ServiceDescriptor(typeof(IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine("), options.DefaultHandlerLifetime));");
        }

        foreach (NotificationHandlerModel handler in model.NotificationHandlers)
        {
            sb.Append("        services.TryAddEnumerable(new ServiceDescriptor(typeof(INotificationHandler<")
                .Append(handler.NotificationFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine("), options.DefaultHandlerLifetime));");
        }

        foreach (StreamRequestHandlerModel handler in model.StreamRequestHandlers)
        {
            sb.Append("        services.TryAdd(new ServiceDescriptor(typeof(IStreamRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine("), options.DefaultHandlerLifetime));");
        }

        sb.AppendLine("        services.TryAddScoped<PlaxionMediatorSender>();");
        sb.AppendLine("        services.TryAddScoped<ISender>(sp => sp.GetRequiredService<PlaxionMediatorSender>());");
        sb.AppendLine("        services.TryAddScoped<IPublisher>(sp => sp.GetRequiredService<PlaxionMediatorSender>());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitSender(GenerationModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PlaxionMediator.Abstractions;");
        sb.AppendLine("using PlaxionMediator.Core;");
        sb.AppendLine("using PlaxionMediator.Pipeline;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.Append("namespace ").Append(model.RootNamespace).AppendLine(".Generated;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class PlaxionMediatorSender : ISender, IPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _services;");
        sb.AppendLine("    private readonly bool _cacheHandlersPerScope;");
        sb.AppendLine("    // Scope-local cache of resolved behavior arrays (used only when no Transient behaviors are registered).");
        sb.AppendLine("    private System.Collections.Generic.Dictionary<System.Type, object>? _behaviorScopeCache;");
        // One nullable handler field per known request type (populated lazily when caching is enabled).
        int handlerFieldIndex = 0;
        foreach (RequestHandlerModel handlerModel in model.RequestHandlers)
        {
            sb.Append("    private IRequestHandler<")
                .Append(handlerModel.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handlerModel.ResponseFullyQualifiedName)
                .Append(">? _cachedHandler")
                .Append(handlerFieldIndex)
                .AppendLine(";");
            handlerFieldIndex++;
        }

        sb.AppendLine();
        sb.AppendLine("    public PlaxionMediatorSender(IServiceProvider services)");
        sb.AppendLine("    {");
        sb.AppendLine("        _services = services ?? throw new ArgumentNullException(nameof(services));");
        sb.AppendLine("        _cacheHandlersPerScope = RequestHandlerResolver.CanCacheHandlersPerScope();");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitSend(sb, model);
        EmitCreateStream(sb, model);
        EmitPublish(sb, model);

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    private static ValueTask<TResponse> CastOrAdapt<TActual, TResponse>(ValueTask<TActual> source)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Fast path: identical closed response types — reinterpret ValueTask without async state machine.");
        sb.AppendLine("        if (typeof(TActual) == typeof(TResponse))");
        sb.AppendLine("        {");
        sb.AppendLine("            return Unsafe.As<ValueTask<TActual>, ValueTask<TResponse>>(ref source);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return Adapt<TActual, TResponse>(source);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static async ValueTask<TResponse> Adapt<TActual, TResponse>(ValueTask<TActual> source)");
        sb.AppendLine("    {");
        sb.AppendLine("        TActual result = await source.ConfigureAwait(false);");
        sb.AppendLine("        return (TResponse)(object)result!;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static async IAsyncEnumerable<TResponse> AdaptStream<TActual, TResponse>(");
        sb.AppendLine("        IAsyncEnumerable<TActual> source,");
        sb.AppendLine("        [EnumeratorCancellation] CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        await foreach (TActual item in source.WithCancellation(cancellationToken).ConfigureAwait(false))");
        sb.AppendLine("        {");
        sb.AppendLine("            yield return (TResponse)(object)item!;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitSend(StringBuilder sb, GenerationModel model)
    {
        sb.AppendLine("    public ValueTask<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (request is null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();

        if (model.RequestHandlers.Length == 0)
        {
            sb.AppendLine("        throw new HandlerNotFoundException(request.GetType());");
        }
        else
        {
            sb.AppendLine("        switch (request)");
            sb.AppendLine("        {");
            int index = 0;
            foreach (RequestHandlerModel handler in model.RequestHandlers)
            {
                string methodName = "SendCore_" + index;
                // CastOrAdapt elides the async adapter when TActual == TResponse (JIT folds the typeof check).
                sb.Append("            case ")
                    .Append(handler.RequestFullyQualifiedName)
                    .Append(" r: return CastOrAdapt<")
                    .Append(handler.ResponseFullyQualifiedName)
                    .Append(", TResponse>(")
                    .Append(methodName)
                    .AppendLine("(r, cancellationToken));");
                index++;
            }

            sb.AppendLine("            default: throw new HandlerNotFoundException(request.GetType());");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        int methodIndex = 0;
        foreach (RequestHandlerModel handler in model.RequestHandlers)
        {
            string methodName = "SendCore_" + methodIndex;
            // AggressiveInlining helps the empty-pipeline TypeVariety path fold into Send's switch.
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.Append("    private ValueTask<")
                .Append(handler.ResponseFullyQualifiedName)
                .Append("> ")
                .Append(methodName)
                .Append('(')
                .Append(handler.RequestFullyQualifiedName)
                .AppendLine(" request, CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            // Resolve handler with optional scope-local cache (safe for Scoped/Singleton registrations).
            sb.Append("        IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">? handler = _cachedHandler")
                .Append(methodIndex)
                .AppendLine(";");
            sb.AppendLine("        if (handler is null)");
            sb.AppendLine("        {");
            sb.Append("            handler = _services.GetRequiredService<IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">>();");
            sb.AppendLine("            if (_cacheHandlersPerScope)");
            sb.AppendLine("            {");
            sb.Append("                _cachedHandler").Append(methodIndex).AppendLine(" = handler;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            // Global fast path: no pipeline behaviors registered anywhere → skip per-type lookup.
            sb.AppendLine("        if (PipelineBehaviorResolver.HasNoPipelineBehaviors())");
            sb.AppendLine("        {");
            sb.AppendLine("            return handler.Handle(request, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.Append("        System.Collections.Generic.IReadOnlyList<IPipelineBehavior<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">> behaviors = PipelineBehaviorResolver.GetBehaviors<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">(_services, ref _behaviorScopeCache);");
            sb.AppendLine("        if (behaviors.Count == 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            return handler.Handle(request, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
            // Pass the handler instance (not handler.Handle method-group) to avoid a per-call Func alloc.
            sb.AppendLine("        return PipelineComposer.ExecuteAsync(request, behaviors, handler, cancellationToken);");
            sb.AppendLine("    }");
            sb.AppendLine();
            methodIndex++;
        }
    }

    private static void EmitCreateStream(StringBuilder sb, GenerationModel model)
    {
        sb.AppendLine("    public IAsyncEnumerable<TResponse> CreateStream<TResponse>(IStreamRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (request is null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();

        if (model.StreamRequestHandlers.Length == 0)
        {
            sb.AppendLine("        throw new HandlerNotFoundException(request.GetType());");
        }
        else
        {
            sb.AppendLine("        switch (request)");
            sb.AppendLine("        {");
            int index = 0;
            foreach (StreamRequestHandlerModel handler in model.StreamRequestHandlers)
            {
                string methodName = "CreateStreamCore_" + index;
                sb.Append("            case ")
                    .Append(handler.RequestFullyQualifiedName)
                    .Append(" r: return AdaptStream<")
                    .Append(handler.ResponseFullyQualifiedName)
                    .Append(", TResponse>(")
                    .Append(methodName)
                    .AppendLine("(r, cancellationToken), cancellationToken);");
                index++;
            }

            sb.AppendLine("            default: throw new HandlerNotFoundException(request.GetType());");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        int methodIndex = 0;
        foreach (StreamRequestHandlerModel handler in model.StreamRequestHandlers)
        {
            string methodName = "CreateStreamCore_" + methodIndex;
            sb.Append("    private async IAsyncEnumerable<")
                .Append(handler.ResponseFullyQualifiedName)
                .Append("> ")
                .Append(methodName)
                .Append('(')
                .Append(handler.RequestFullyQualifiedName)
                .AppendLine(" request, [EnumeratorCancellation] CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            sb.Append("        IStreamRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append("> handler = _services.GetRequiredService<IStreamRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">>();");
            sb.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("        await foreach (" + handler.ResponseFullyQualifiedName + " item in handler.Handle(request, cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))");
            sb.AppendLine("        {");
            sb.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            sb.AppendLine("            yield return item;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            methodIndex++;
        }
    }

    private static void EmitPublish(StringBuilder sb, GenerationModel model)
    {
        sb.AppendLine("    public async ValueTask Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("        where TNotification : INotification");
        sb.AppendLine("    {");
        sb.AppendLine("        if (notification is null) throw new ArgumentNullException(nameof(notification));");
        sb.AppendLine();

        List<IGrouping<string, NotificationHandlerModel>> notificationGroups = model.NotificationHandlers
            .GroupBy(h => h.NotificationFullyQualifiedName)
            .ToList();

        if (notificationGroups.Count == 0)
        {
            sb.AppendLine("        await default(ValueTask);");
        }
        else
        {
            sb.AppendLine("        switch (notification)");
            sb.AppendLine("        {");
            int nIndex = 0;
            foreach (IGrouping<string, NotificationHandlerModel> group in notificationGroups)
            {
                string methodName = "PublishCore_" + nIndex;
                sb.Append("            case ")
                    .Append(group.Key)
                    .Append(" n: await ")
                    .Append(methodName)
                    .AppendLine("(n, cancellationToken); return;");
                nIndex++;
            }

            sb.AppendLine("            default: return;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        int pubIndex = 0;
        foreach (IGrouping<string, NotificationHandlerModel> group in notificationGroups)
        {
            string methodName = "PublishCore_" + pubIndex;
            string strategy = group.Select(h => h.PublishStrategy).FirstOrDefault() ?? "Sequential";
            bool parallel = string.Equals(strategy, "Parallel", System.StringComparison.Ordinal);

            sb.Append("    private async ValueTask ")
                .Append(methodName)
                .Append('(')
                .Append(group.Key)
                .AppendLine(" notification, CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            sb.Append("        // PublishStrategy.")
                .Append(strategy)
                .AppendLine(" (source-generator emitted)");
            sb.Append("        INotificationHandler<")
                .Append(group.Key)
                .Append(">[] handlers = _services.GetServices<INotificationHandler<")
                .Append(group.Key)
                .AppendLine(">>().ToArray();");

            if (parallel)
            {
                sb.AppendLine("        if (handlers.Length == 0)");
                sb.AppendLine("        {");
                sb.AppendLine("            return;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        Task<Exception?>[] tasks = new Task<Exception?>[handlers.Length];");
                sb.AppendLine("        for (int i = 0; i < handlers.Length; i++)");
                sb.AppendLine("        {");
                sb.AppendLine("            INotificationHandler<" + group.Key + "> handler = handlers[i];");
                sb.AppendLine("            tasks[i] = InvokeParallel(handler, notification, cancellationToken);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        Exception?[] results = await Task.WhenAll(tasks).ConfigureAwait(false);");
                sb.AppendLine("        List<Exception>? exceptions = null;");
                sb.AppendLine("        for (int i = 0; i < results.Length; i++)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (results[i] is null)");
                sb.AppendLine("            {");
                sb.AppendLine("                continue;");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine("            exceptions ??= new List<Exception>();");
                sb.AppendLine("            exceptions.Add(results[i]!);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        if (exceptions is { Count: 1 }) throw exceptions[0];");
                sb.AppendLine("        if (exceptions is { Count: > 1 }) throw new AggregateException(exceptions);");
                sb.AppendLine();
                sb.AppendLine("        static async Task<Exception?> InvokeParallel(");
                sb.AppendLine("            INotificationHandler<" + group.Key + "> handler,");
                sb.AppendLine("            " + group.Key + " notification,");
                sb.AppendLine("            CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine("                await handler.Handle(notification, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("                return null;");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                return ex;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine("        List<Exception>? exceptions = null;");
                sb.AppendLine("        foreach (INotificationHandler<" + group.Key + "> handler in handlers)");
                sb.AppendLine("        {");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine("                await handler.Handle(notification, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                exceptions ??= new List<Exception>();");
                sb.AppendLine("                exceptions.Add(ex);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        if (exceptions is { Count: 1 }) throw exceptions[0];");
                sb.AppendLine("        if (exceptions is { Count: > 1 }) throw new AggregateException(exceptions);");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            pubIndex++;
        }
    }
}
