blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/avmp2208/PlaxionMediator/discussions
    about: Please ask general questions here instead of opening an issue.
