using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Conduit.SourceGenerators;

internal static class SourceEmitter
{
    public static string EmitRegistration(GenerationModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Conduit.Abstractions;");
        sb.AppendLine("using Conduit.Core;");
        sb.AppendLine("using Conduit.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.Append("namespace ").Append(model.RootNamespace).AppendLine(".Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class ConduitRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        ConduitGeneratedRegistrationBridge.Register = Register;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static void Register(IServiceCollection services, ConduitOptions options)");
        sb.AppendLine("    {");

        foreach (RequestHandlerModel handler in model.RequestHandlers)
        {
            sb.Append("        services.TryAdd(new ServiceDescriptor(typeof(IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine("), options.DefaultHandlerLifetime));");
        }

        foreach (NotificationHandlerModel handler in model.NotificationHandlers)
        {
            sb.Append("        services.TryAddEnumerable(new ServiceDescriptor(typeof(INotificationHandler<")
                .Append(handler.NotificationFullyQualifiedName)
                .Append(">), typeof(")
                .Append(handler.HandlerFullyQualifiedName)
                .AppendLine("), options.DefaultHandlerLifetime));");
        }

        sb.AppendLine("        services.TryAddScoped<ConduitSender>();");
        sb.AppendLine("        services.TryAddScoped<ISender>(sp => sp.GetRequiredService<ConduitSender>());");
        sb.AppendLine("        services.TryAddScoped<IPublisher>(sp => sp.GetRequiredService<ConduitSender>());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string EmitSender(GenerationModel model)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Conduit.Abstractions;");
        sb.AppendLine("using Conduit.Core;");
        sb.AppendLine("using Conduit.Pipeline;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.Append("namespace ").Append(model.RootNamespace).AppendLine(".Generated;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class ConduitSender : ISender, IPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _services;");
        sb.AppendLine();
        sb.AppendLine("    public ConduitSender(IServiceProvider services)");
        sb.AppendLine("    {");
        sb.AppendLine("        _services = services ?? throw new ArgumentNullException(nameof(services));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public ValueTask<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (request is null) throw new ArgumentNullException(nameof(request));");
        sb.AppendLine();

        if (model.RequestHandlers.Length == 0)
        {
            sb.AppendLine("        throw new HandlerNotFoundException(request.GetType());");
        }
        else
        {
            sb.AppendLine("        switch (request)");
            sb.AppendLine("        {");
            int index = 0;
            foreach (RequestHandlerModel handler in model.RequestHandlers)
            {
                string methodName = "SendCore_" + index;
                sb.Append("            case ")
                    .Append(handler.RequestFullyQualifiedName)
                    .Append(" r: return Adapt<")
                    .Append(handler.ResponseFullyQualifiedName)
                    .Append(", TResponse>(")
                    .Append(methodName)
                    .AppendLine("(r, cancellationToken));");
                index++;
            }

            sb.AppendLine("            default: throw new HandlerNotFoundException(request.GetType());");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        int methodIndex = 0;
        foreach (RequestHandlerModel handler in model.RequestHandlers)
        {
            string methodName = "SendCore_" + methodIndex;
            sb.Append("    private ValueTask<")
                .Append(handler.ResponseFullyQualifiedName)
                .Append("> ")
                .Append(methodName)
                .Append('(')
                .Append(handler.RequestFullyQualifiedName)
                .AppendLine(" request, CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            sb.Append("        IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append("> handler = _services.GetRequiredService<IRequestHandler<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">>();");
            sb.Append("        IPipelineBehavior<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .Append(">[] behaviors = _services.GetServices<IPipelineBehavior<")
                .Append(handler.RequestFullyQualifiedName)
                .Append(", ")
                .Append(handler.ResponseFullyQualifiedName)
                .AppendLine(">>().ToArray();");
            sb.AppendLine("        if (behaviors.Length == 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            return handler.Handle(request, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        return PipelineComposer.ExecuteAsync(request, behaviors, handler.Handle, cancellationToken);");
            sb.AppendLine("    }");
            sb.AppendLine();
            methodIndex++;
        }

        sb.AppendLine("    public async ValueTask Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
        sb.AppendLine("        where TNotification : INotification");
        sb.AppendLine("    {");
        sb.AppendLine("        if (notification is null) throw new ArgumentNullException(nameof(notification));");
        sb.AppendLine();

        List<IGrouping<string, NotificationHandlerModel>> notificationGroups = model.NotificationHandlers
            .GroupBy(h => h.NotificationFullyQualifiedName)
            .ToList();

        if (notificationGroups.Count == 0)
        {
            sb.AppendLine("        await default(ValueTask);");
        }
        else
        {
            sb.AppendLine("        switch (notification)");
            sb.AppendLine("        {");
            int nIndex = 0;
            foreach (IGrouping<string, NotificationHandlerModel> group in notificationGroups)
            {
                string methodName = "PublishCore_" + nIndex;
                sb.Append("            case ")
                    .Append(group.Key)
                    .Append(" n: await ")
                    .Append(methodName)
                    .AppendLine("(n, cancellationToken); return;");
                nIndex++;
            }

            sb.AppendLine("            default: return;");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        int pubIndex = 0;
        foreach (IGrouping<string, NotificationHandlerModel> group in notificationGroups)
        {
            string methodName = "PublishCore_" + pubIndex;
            sb.Append("    private async ValueTask ")
                .Append(methodName)
                .Append('(')
                .Append(group.Key)
                .AppendLine(" notification, CancellationToken cancellationToken)");
            sb.AppendLine("    {");
            sb.Append("        IEnumerable<INotificationHandler<")
                .Append(group.Key)
                .Append(">> handlers = _services.GetServices<INotificationHandler<")
                .Append(group.Key)
                .AppendLine(">>();");
            sb.AppendLine("        List<Exception>? exceptions = null;");
            sb.AppendLine("        foreach (INotificationHandler<" + group.Key + "> handler in handlers)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                await handler.Handle(notification, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                exceptions ??= new List<Exception>();");
            sb.AppendLine("                exceptions.Add(ex);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (exceptions is { Count: 1 }) throw exceptions[0];");
            sb.AppendLine("        if (exceptions is { Count: > 1 }) throw new AggregateException(exceptions);");
            sb.AppendLine("    }");
            sb.AppendLine();
            pubIndex++;
        }

        sb.AppendLine("    private static async ValueTask<TResponse> Adapt<TActual, TResponse>(ValueTask<TActual> source)");
        sb.AppendLine("    {");
        sb.AppendLine("        TActual result = await source.ConfigureAwait(false);");
        sb.AppendLine("        return (TResponse)(object)result!;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
