<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageVersion Include="MediatR" Version="12.5.0" />
    <PackageVersion Include="Mediator.SourceGenerator" Version="3.0.2" />
    <PackageVersion Include="Mediator.Abstractions" Version="3.0.2" />
  </ItemGroup>
</Project>
